name: Update TEFAS/Fintables Data

on:
  workflow_dispatch:   # Manuel tetikleme için
  schedule:
    - cron: '0 6 * * *'   # Her gün sabah 06:00 UTC çalıştır

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run TEFAS script
        run: python scripts/fetch_tefas.py

      - name: Run Fintables script
        run: python scripts/fetch_fintables.py

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/latest.json
          git commit -m "Update data"
          git push
